# Generated by Django 5.2 on 2025-04-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laureate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fact', models.TextField()),
                ('q1_answer', models.CharField(max_length=50)),
                ('q2_answer', models.CharField(max_length=50)),
                ('q3_answer', models.CharField(max_length=50)),
                ('q4_answer', models.CharField(max_length=50)),
            ],
        ),
    ]
